/**
 * Mock data for local development without a Supabase project.
 * Enabled when NEXT_PUBLIC_MOCK_AUTH=true in .env.local
 */
import { Profile, Subscription, Claim, Plan, FamilyMember, PaymentRecord, AppNotification, Doctor } from '@/types';

export const MOCK_PROFILE: Profile = {
  id: 'mock-user-001',
  full_name: 'Demo User',
  nrc: '123456/78/1',
  date_of_birth: '1990-06-15',
  gender: 'male',
  phone: '+260971234567',
  avatar_url: null,
  role: 'admin', // admin so /admin page is accessible too
  created_at: new Date('2026-01-01').toISOString(),
  updated_at: new Date('2026-01-01').toISOString(),
};

export const MOCK_PLAN: Plan = {
  id: 'plan-standard',
  name: 'Standard Health',
  price: 350,
  description: 'Comprehensive cover for families with outpatient and inpatient benefits.',
  features: ['Unlimited GP Visits', 'Specialist Referrals', 'Hospitalization (7 days)', 'Medication Cover', 'Dental Basic', 'Eye Tests'],
  coverage_details: [
    { category: 'Outpatient', limit: 'Unlimited', description: 'All GP and specialist visits' },
    { category: 'Inpatient', limit: 'ZMW 50,000/year', description: 'Hospital stays up to 7 days' },
    { category: 'Medication', limit: 'ZMW 1,500/month', description: 'All prescribed medications' },
  ],
  is_active: true,
  color: 'from-accent-500 to-accent-700',
  created_at: new Date('2026-01-01').toISOString(),
};

export const MOCK_SUBSCRIPTION: Subscription = {
  id: 'sub-mock-001',
  user_id: 'mock-user-001',
  plan_id: 'plan-standard',
  status: 'active',
  start_date: new Date('2026-01-01').toISOString(),
  end_date: new Date('2027-01-01').toISOString(),
  policy_number: 'NH-2026-00042',
  created_at: new Date('2026-01-01').toISOString(),
  plan: MOCK_PLAN,
};

export const MOCK_CLAIMS: Claim[] = [
  {
    id: 'claim-001',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    member_id: null,
    type: 'consultation',
    amount: 250,
    status: 'paid',
    notes: 'Annual checkup at City Clinic',
    receipt_url: null,
    created_at: new Date('2026-04-01').toISOString(),
    updated_at: new Date('2026-04-05').toISOString(),
  },
  {
    id: 'claim-002',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    member_id: 'fam-001',
    type: 'medication',
    amount: 180,
    status: 'approved',
    notes: 'Amoxicillin 500mg x 14 days',
    receipt_url: null,
    created_at: new Date('2026-04-08').toISOString(),
    updated_at: new Date('2026-04-10').toISOString(),
  },
  {
    id: 'claim-003',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    member_id: 'fam-002',
    type: 'lab',
    amount: 420,
    status: 'reviewing',
    notes: 'Full blood count + cholesterol panel',
    receipt_url: null,
    created_at: new Date('2026-04-12').toISOString(),
    updated_at: new Date('2026-04-12').toISOString(),
  },
  {
    id: 'claim-004',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    member_id: null,
    type: 'dental',
    amount: 600,
    status: 'submitted',
    notes: 'Tooth extraction — upper right molar',
    receipt_url: null,
    created_at: new Date('2026-04-15').toISOString(),
    updated_at: new Date('2026-04-15').toISOString(),
  },
  {
    id: 'claim-005',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    member_id: null,
    type: 'consultation',
    amount: 300,
    status: 'rejected',
    notes: 'Specialist visit — not pre-authorised',
    receipt_url: null,
    created_at: new Date('2026-03-20').toISOString(),
    updated_at: new Date('2026-03-25').toISOString(),
  },
];

// ─── Family Members ──────────────────────────────────────────────────────────

export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'fam-001',
    user_id: 'mock-user-001',
    name: 'Grace Mwale',
    relationship: 'spouse',
    date_of_birth: '1992-03-18',
    gender: 'female',
    plan_id: 'plan-standard',
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'fam-002',
    user_id: 'mock-user-001',
    name: 'Liam Mwale',
    relationship: 'child',
    date_of_birth: '2018-07-04',
    gender: 'male',
    plan_id: 'plan-standard',
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'fam-003',
    user_id: 'mock-user-001',
    name: 'Amara Mwale',
    relationship: 'child',
    date_of_birth: '2021-11-22',
    gender: 'female',
    plan_id: null,
    created_at: new Date('2026-02-14').toISOString(),
  },
];

// ─── Payments ────────────────────────────────────────────────────────────────

export const MOCK_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    amount: 350,
    currency: 'ZMW',
    status: 'success',
    method: 'mtn_momo',
    reference: 'MTN-20260401-1234',
    description: 'Standard Health — April 2026',
    created_at: new Date('2026-04-01').toISOString(),
  },
  {
    id: 'pay-002',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    amount: 350,
    currency: 'ZMW',
    status: 'success',
    method: 'mtn_momo',
    reference: 'MTN-20260301-9812',
    description: 'Standard Health — March 2026',
    created_at: new Date('2026-03-01').toISOString(),
  },
  {
    id: 'pay-003',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    amount: 350,
    currency: 'ZMW',
    status: 'failed',
    method: 'airtel_money',
    reference: 'AIR-20260201-5500',
    description: 'Standard Health — February 2026',
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'pay-004',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    amount: 350,
    currency: 'ZMW',
    status: 'success',
    method: 'mtn_momo',
    reference: 'MTN-20260201-7441',
    description: 'Standard Health — February 2026 (retry)',
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'pay-005',
    user_id: 'mock-user-001',
    subscription_id: 'sub-mock-001',
    amount: 350,
    currency: 'ZMW',
    status: 'success',
    method: 'mtn_momo',
    reference: 'MTN-20260101-3301',
    description: 'Standard Health — January 2026',
    created_at: new Date('2026-01-01').toISOString(),
  },
];

// ─── Notifications ───────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-001',
    user_id: 'mock-user-001',
    type: 'claim_update',
    title: 'Claim Approved',
    message: 'Your consultation claim of ZMW 450 has been approved.',
    read: false,
    action_href: '/claims/claim-003',
    created_at: new Date('2026-04-16T10:30:00').toISOString(),
  },
  {
    id: 'notif-002',
    user_id: 'mock-user-001',
    type: 'payment_reminder',
    title: 'Payment Due Soon',
    message: 'Your Standard Health plan renews on May 1. Ensure your MoMo wallet is funded.',
    read: false,
    action_href: '/payments',
    created_at: new Date('2026-04-15T08:00:00').toISOString(),
  },
  {
    id: 'notif-003',
    user_id: 'mock-user-001',
    type: 'coverage_status',
    title: 'Coverage Active',
    message: 'Your NuroCare Standard Health plan is active and covers you through April 30.',
    read: true,
    action_href: '/plans',
    created_at: new Date('2026-04-01T09:00:00').toISOString(),
  },
  {
    id: 'notif-004',
    user_id: 'mock-user-001',
    type: 'claim_update',
    title: 'Claim Under Review',
    message: 'Your lab test claim submitted on April 10 is currently being reviewed.',
    read: true,
    action_href: '/claims/claim-004',
    created_at: new Date('2026-04-12T14:20:00').toISOString(),
  },
  {
    id: 'notif-005',
    user_id: 'mock-user-001',
    type: 'general',
    title: 'Welcome to NuroCare',
    message: 'Your account is set up. Explore your benefits and find care near you.',
    read: true,
    action_href: '/dashboard',
    created_at: new Date('2026-01-01T07:00:00').toISOString(),
  },
];

// ─── Doctors ─────────────────────────────────────────────────────────────────

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-001',
    name: 'Dr. Chanda Mwila',
    specialty: 'general',
    qualifications: 'MBChB, UNZA',
    experience_years: 8,
    languages: ['English', 'Bemba', 'Nyanja'],
    availability: 'available',
    rating: 4.8,
    consult_count: 312,
    whatsapp_number: '260971000001',
    avatar_initials: 'CM',
    avatar_color: 'bg-accent-500',
  },
  {
    id: 'doc-002',
    name: 'Dr. Nkandu Banda',
    specialty: 'paediatrics',
    qualifications: 'MBChB, DCH',
    experience_years: 12,
    languages: ['English', 'Nyanja'],
    availability: 'busy',
    next_available: '14:30',
    rating: 4.9,
    consult_count: 541,
    whatsapp_number: '260971000002',
    avatar_initials: 'NB',
    avatar_color: 'bg-blue-500',
  },
  {
    id: 'doc-003',
    name: 'Dr. Mutinta Phiri',
    specialty: 'mental_health',
    qualifications: 'MBChB, MRCPsych',
    experience_years: 6,
    languages: ['English', 'Tonga'],
    availability: 'available',
    rating: 4.7,
    consult_count: 198,
    whatsapp_number: '260971000003',
    avatar_initials: 'MP',
    avatar_color: 'bg-violet-500',
  },
  {
    id: 'doc-004',
    name: 'Dr. Abel Sinkala',
    specialty: 'dermatology',
    qualifications: 'MBChB, Dip Derm',
    experience_years: 10,
    languages: ['English', 'Bemba'],
    availability: 'offline',
    next_available: 'Tomorrow 09:00',
    rating: 4.6,
    consult_count: 267,
    whatsapp_number: '260971000004',
    avatar_initials: 'AS',
    avatar_color: 'bg-warning-500',
  },
  {
    id: 'doc-005',
    name: 'Dr. Charity Tembo',
    specialty: 'gynaecology',
    qualifications: 'MBChB, MRCOG',
    experience_years: 15,
    languages: ['English', 'Nyanja', 'Bemba'],
    availability: 'available',
    rating: 4.9,
    consult_count: 723,
    whatsapp_number: '260971000005',
    avatar_initials: 'CT',
    avatar_color: 'bg-rose-500',
  },
];
