import { Facility } from '@/types';

// Centred around Lusaka, Zambia (-15.4166, 28.2833)
export const MOCK_FACILITIES: Facility[] = [
  // ── Hospitals ─────────────────────────────────────────────────────────────
  {
    id: 'fac-001',
    name: 'University Teaching Hospital',
    type: 'hospital',
    address: 'Nationalist Road, Lusaka',
    phone: '+260 211 254 131',
    distance_km: 1.2,
    covered: true,
    open_now: true,
    hours: 'Open 24 hours',
    services: ['Emergency', 'Surgery', 'Maternity', 'Paediatrics', 'ICU', 'Radiology'],
    lat: -15.4117,
    lng: 28.2996,
    rating: 4.1,
  },
  {
    id: 'fac-002',
    name: 'Maina Soko Military Hospital',
    type: 'hospital',
    address: 'Leopards Hill Road, Lusaka',
    phone: '+260 211 273 044',
    distance_km: 3.8,
    covered: true,
    open_now: true,
    hours: 'Open 24 hours',
    services: ['Emergency', 'Orthopaedics', 'Surgery', 'General Medicine'],
    lat: -15.3880,
    lng: 28.3320,
    rating: 3.9,
  },
  {
    id: 'fac-003',
    name: 'Levy Mwanawasa General Hospital',
    type: 'hospital',
    address: 'Church Road, Lusaka',
    phone: '+260 211 222 821',
    distance_km: 2.1,
    covered: false,
    open_now: true,
    hours: 'Open 24 hours',
    services: ['Emergency', 'Maternity', 'Paediatrics', 'General Medicine'],
    lat: -15.4234,
    lng: 28.2785,
    rating: 3.7,
  },
  {
    id: 'fac-004',
    name: 'Lusaka Trust Hospital',
    type: 'hospital',
    address: '2 Paseli Road, Northmead, Lusaka',
    phone: '+260 211 234 567',
    distance_km: 4.5,
    covered: true,
    open_now: false,
    hours: 'Mon–Sat 07:00–22:00',
    services: ['Outpatient', 'Surgery', 'Oncology', 'Cardiology', 'Dental'],
    lat: -15.3970,
    lng: 28.3150,
    rating: 4.4,
  },

  // ── Clinics ────────────────────────────────────────────────────────────────
  {
    id: 'fac-005',
    name: 'Care for Business Clinic',
    type: 'clinic',
    address: 'Cairo Road, Lusaka CBD',
    phone: '+260 211 226 065',
    distance_km: 0.7,
    covered: true,
    open_now: true,
    hours: 'Mon–Fri 08:00–17:00',
    services: ['GP Consultations', 'Blood Tests', 'Vaccinations', 'Occupational Health'],
    lat: -15.4165,
    lng: 28.2831,
    rating: 4.6,
  },
  {
    id: 'fac-006',
    name: 'Crossroads Medical Centre',
    type: 'clinic',
    address: 'Crossroads, Woodlands, Lusaka',
    phone: '+260 211 262 099',
    distance_km: 5.3,
    covered: true,
    open_now: true,
    hours: 'Daily 07:30–21:00',
    services: ['GP', 'Specialist Referrals', 'Ultrasound', 'Minor Surgery'],
    lat: -15.4410,
    lng: 28.3220,
    rating: 4.3,
  },
  {
    id: 'fac-007',
    name: 'Avic International Health Centre',
    type: 'clinic',
    address: 'East Park Mall, Thabo Mbeki Road',
    phone: '+260 960 000 099',
    distance_km: 3.2,
    covered: false,
    open_now: true,
    hours: 'Mon–Sat 08:00–20:00',
    services: ['GP Consultations', 'Dental', 'Eye Tests', 'Pharmacy'],
    lat: -15.4070,
    lng: 28.3340,
    rating: 4.2,
  },
  {
    id: 'fac-008',
    name: 'Chainama Hills Health Centre',
    type: 'clinic',
    address: 'Chainama Hills, Lusaka East',
    phone: '+260 211 276 510',
    distance_km: 7.1,
    covered: true,
    open_now: false,
    hours: 'Mon–Fri 08:00–16:30',
    services: ['Mental Health', 'GP', 'Counselling', 'Psychiatry'],
    lat: -15.3730,
    lng: 28.3560,
    rating: 3.8,
  },

  // ── Pharmacies ─────────────────────────────────────────────────────────────
  {
    id: 'fac-009',
    name: 'Zambia Pharmacy (Cairo Road)',
    type: 'pharmacy',
    address: 'Cairo Road, Central Lusaka',
    phone: '+260 211 226 500',
    distance_km: 0.4,
    covered: true,
    open_now: true,
    hours: 'Mon–Sat 08:00–18:00',
    services: ['Prescription Dispensing', 'OTC Medicines', 'Health Advice'],
    lat: -15.4160,
    lng: 28.2840,
    rating: 4.0,
  },
  {
    id: 'fac-010',
    name: 'Clicks Pharmacy — Manda Hill',
    type: 'pharmacy',
    address: 'Manda Hill Mall, Great East Road',
    phone: '+260 211 257 888',
    distance_km: 2.9,
    covered: true,
    open_now: true,
    hours: 'Daily 08:00–21:00',
    services: ['Prescription Drugs', 'Baby & Mother', 'Cosmetics', 'Health Monitoring'],
    lat: -15.3985,
    lng: 28.3240,
    rating: 4.5,
  },
  {
    id: 'fac-011',
    name: 'Pep Pharmacy — Arcades',
    type: 'pharmacy',
    address: 'Arcades Shopping Centre, Great East Road',
    phone: '+260 211 290 100',
    distance_km: 4.1,
    covered: false,
    open_now: true,
    hours: 'Daily 09:00–20:00',
    services: ['OTC Medicines', 'Vitamins & Supplements', 'Prescription Dispensing'],
    lat: -15.3920,
    lng: 28.3410,
    rating: 3.9,
  },
  {
    id: 'fac-012',
    name: 'HealthPlus Pharmacy — Kabulonga',
    type: 'pharmacy',
    address: 'Kabulonga Road, Lusaka',
    phone: '+260 976 543 210',
    distance_km: 6.0,
    covered: true,
    open_now: false,
    hours: 'Mon–Sat 08:00–19:00',
    services: ['24hr Emergency Dispensing', 'Chronic Medication', 'Health Screening'],
    lat: -15.4450,
    lng: 28.3080,
    rating: 4.7,
  },
];

export function getFacilityById(id: string): Facility | undefined {
  return MOCK_FACILITIES.find((f) => f.id === id);
}
