import { Drug } from '@/types';

/**
 * Mock drug database — replace with real API (e.g. RxNorm, OpenFDA) later.
 */
export const MOCK_DRUGS: Drug[] = [
  {
    id: '1',
    name: 'Paracetamol',
    generic_name: 'Acetaminophen',
    usage: 'Relief of mild to moderate pain and fever reduction',
    dosage: 'Adults: 500mg–1g every 4–6 hours (max 4g/day). Children: 15mg/kg every 4–6 hours.',
    side_effects: ['Nausea', 'Rash (rare)', 'Liver damage (overdose)'],
    category: 'Analgesic / Antipyretic',
    prescription_required: false,
  },
  {
    id: '2',
    name: 'Amoxicillin',
    generic_name: 'Amoxicillin trihydrate',
    usage: 'Treatment of bacterial infections (respiratory, urinary, skin)',
    dosage: 'Adults: 250–500mg every 8 hours for 5–10 days as directed.',
    side_effects: ['Diarrhea', 'Rash', 'Nausea', 'Allergic reaction'],
    category: 'Antibiotic',
    prescription_required: true,
  },
  {
    id: '3',
    name: 'Metformin',
    generic_name: 'Metformin hydrochloride',
    usage: 'Management of type 2 diabetes mellitus',
    dosage: 'Starting dose: 500mg twice daily with meals. Max: 2000–2550mg/day.',
    side_effects: ['Nausea', 'Diarrhea', 'Stomach upset', 'Lactic acidosis (rare)'],
    category: 'Antidiabetic',
    prescription_required: true,
  },
  {
    id: '4',
    name: 'Lisinopril',
    generic_name: 'Lisinopril',
    usage: 'Treatment of high blood pressure and heart failure',
    dosage: 'Adults: 10mg once daily, may increase to 40mg/day.',
    side_effects: ['Dry cough', 'Dizziness', 'Headache', 'Hyperkalemia'],
    category: 'ACE Inhibitor',
    prescription_required: true,
  },
  {
    id: '5',
    name: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    usage: 'Relief of pain, fever, and inflammation',
    dosage: 'Adults: 200–400mg every 4–6 hours (max 1200mg/day OTC).',
    side_effects: ['Stomach upset', 'Heartburn', 'Dizziness', 'Kidney issues (long-term)'],
    category: 'NSAID',
    prescription_required: false,
  },
  {
    id: '6',
    name: 'Atorvastatin',
    generic_name: 'Atorvastatin calcium',
    usage: 'Lowering cholesterol and reducing risk of cardiovascular disease',
    dosage: 'Adults: 10–80mg once daily, usually taken in the evening.',
    side_effects: ['Muscle pain', 'Liver enzyme elevation', 'Headache', 'Nausea'],
    category: 'Statin',
    prescription_required: true,
  },
  {
    id: '7',
    name: 'Artemether/Lumefantrine',
    generic_name: 'Artemether + Lumefantrine',
    usage: 'Treatment of uncomplicated malaria caused by Plasmodium falciparum',
    dosage: '6 doses over 3 days. Weight-based dosing for children.',
    side_effects: ['Headache', 'Dizziness', 'Loss of appetite', 'Joint pain'],
    category: 'Antimalarial',
    prescription_required: true,
  },
  {
    id: '8',
    name: 'Omeprazole',
    generic_name: 'Omeprazole',
    usage: 'Treatment of acid reflux, peptic ulcers, and GERD',
    dosage: 'Adults: 20–40mg once daily before breakfast.',
    side_effects: ['Headache', 'Diarrhea', 'Nausea', 'Abdominal pain'],
    category: 'Proton Pump Inhibitor',
    prescription_required: false,
  },
];
